foo: 1.0.0
#spring配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.2.121:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
